name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
      - '.github/workflows/markdown-lint.yml'
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/markdown-lint.yml'

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install markdownlint-cli
      run: |
        npm install -g markdownlint-cli

    - name: Lint Markdown Files
      run: |
        find . -name "*.md" -not -path "./node_modules/*" -exec markdownlint {} \;

    - name: Check Links (for README.md)
      if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
      run: |
        if [ -f README.md ]; then
          npx markdown-link-check README.md --config .github/markdown-link-config.json || true
        fi
